# Generated by Django 4.2 on 2023-07-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0007_news_image_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='anonses/%Y/%m/%d')),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Обьявление',
                'verbose_name_plural': 'Обьявления',
                'ordering': ('pub_date',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('title',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='anonses/%Y/%m/%d'),
        ),
    ]
