# Generated by Django 4.2 on 2023-07-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0014_alter_post_category_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mySite.post'),
        ),
        migrations.AlterField(
            model_name='postlink',
            name='url',
            field=models.URLField(verbose_name='Ссылки'),
        ),
    ]
