# Generated by Django 4.2 on 2023-07-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0018_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name2',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Санат атауы(каз)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=1, verbose_name='Текст (каз)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default=0, max_length=200, verbose_name='Тақырып (каз)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Имя категории(рус)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Текст(рус)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок (рус)'),
        ),
    ]
