# Generated by Django 4.2 on 2023-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0019_category_name2_post_content2_post_title2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name2',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Санат атауы(каз)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(default='', verbose_name='Текст (каз)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(default='', max_length=200, verbose_name='Тақырып (каз)'),
        ),
    ]
