# Generated by Django 4.2 on 2023-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0020_alter_category_name2_alter_post_content2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title2',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='Заголовок (рус)'), max_length=200, verbose_name='Тақырып (каз)'),
        ),
    ]
