# Generated by Django 4.2 on 2023-07-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0022_alter_post_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlink',
            name='text',
            field=models.CharField(default=0, max_length=200, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
